name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Ruby (2.6)
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Install SQLite
      run: sudo apt install -y libsqlite3-dev

    - name: Install Ruby dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Test with RSpec
      run: bundle exec rspec

    - name: Publish Test Coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: 37aee70bb2e818f3bf4d2af88ea4a4355393901ba98b3876c244d42ed20fdbe1
      with:
        coverageCommand: true
